[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.3.15"

[[constraint]]
  name = "github.com/kelseyhightower/memkv"
  version = "0.1.1"

[[constraint]]
  name = "golang.org/x/net"
  revision = "66aacef3dd8a676686c7ae3716979581e8b03c47"
