[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.3.4"

[[constraint]]
  name = "github.com/kelseyhightower/memkv"
  version = "0.1.1"

[[constraint]]
  name = "golang.org/x/net"
  revision = "66aacef3dd8a676686c7ae3716979581e8b03c47"

[[override]]
  name = "github.com/ugorji/go"
  revision = "bdcc60b419d136a85cdf2e7cbcac34b3f1cd6e57"

[[override]]
  name = "google.golang.org/grpc"
  version = "=1.7.5"

[[override]]
  name = "golang.org/x/crypto"
  revision = "9419663f5a44be8b34ca85f08abc5fe1be11f8a3"

[[override]]
  name = "golang.org/x/sys"
  revision = "ebfc5b4631820b793c9010c87fd8fef0f39eb082"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"
