[template]
mode = "0644"
src = "basic.conf.tmpl"
dest = "/tmp/confd-manykeys-test.conf"
keys = [
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username",
  "/database/host",
  "/database/password",
  "/database/port",
  "/database/username"
]
